apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-task1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:alpine-minimal
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
