apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool:alpine-minimal
        env:
        - name: HTTP_PORT
          value: "1180"
        ports:
        - containerPort: 1180
